import { translate } from 'src/core/helpers/utils';
import BudgetForm from 'src/modules/CreateProject/containers/BudgetForm';
import TwoColumnLayout from 'src/modules/CreateProject/templates/TwoColumnLayout';

export const CreateProjectStep4 = () => {
  return (
    <TwoColumnLayout
      title={'Funding and budget'}
      description={
        <>
          <p className="mb-3">{'Below are some questions to help you start writing. You can always edit it later:'}</p>
          <ul className="list-disc list-inside space-y-2">
            <li>
              {
                'You may choose to allocate $1500 of your secured funds to Socious for impact assessment, or request an external organization to conduct it.'
              }
            </li>
            <li>
              {
                'Contribution to the next round of Socious Fund is not compulsory, but will increase your chances of securing funding. These contributions can be made in various forms, such as equity, tokens, revenue-share, carbon credits, or other value generated by your project. e.g. As a gesture of goodwill and commitment to the success of our project, if awarded by Scoious Fund, we will voluntarily allocate 1% of our equity.'
              }
            </li>
          </ul>
        </>
      }
    >
      <BudgetForm />
    </TwoColumnLayout>
  );
};
