export const ROUNDS = {
    id: "39a37dea-b4ec-488d-a3a0-c784258bf4b9",
    name: "New Round",
    pool_amount: 10000,
    cover_id: null,
    cover: null,
    voting_start_at: "2025-03-28T00:00:00Z",
    voting_end_at: "2025-06-30T00:00:00Z",
    submission_start_at: "2025-03-26T00:00:00Z",
    submission_end_at: "2025-03-27T00:00:00Z",
    total_donations: 941,
    total_votes: 42,
    total_projects: 24,
    voting_announce_at: null,
    created_at: "2025-03-25T18:47:58.241413Z",
    updated_at: "2025-03-25T18:47:58.241413Z"
}

export const IDENTITIES = {
    identities: [
        {
            id: "5f9b98e7-a31b-4622-88d1-2da867f5ffdd",
            type: "organizations",
            meta: {
                bio: null,
                city: null,
                logo: {
                    id: "53172727-71ae-4ed6-9459-0e4e93cf1884",
                    url: "https://storage.googleapis.com/socious-gcs/f63c207fad58219f0d89022ec3e4a614418063b25e29b97a4b03870e0c175892.jpg",
                    filename: "cover photo.jpg",
                    created_at: "2025-03-25T17:36:45.580589Z"
                },
                name: "testorganization",
                cover: {},
                email: "shantisaghoolian@gmail.com",
                phone: null,
                status: "NOT_ACTIVE",
                address: null,
                country: null,
                culture: null,
                mission: null,
                website: null,
                verified: true,
                shortname: "testorganization",
                description: null,
                verified_impact: false
            },
            current: false,
            created_at: "2025-03-25T17:37:38.441352Z",
            updated_at: "2025-05-21T13:48:22.162794Z"
        },
        {
            id: "035f724e-5824-4129-8ed6-96c6dda81a3a",
            type: "users",
            meta: {
                city: null,
                cover: {},
                email: "imshantik@gmail.com",
                avatar: {},
                address: null,
                country: null,
                donates: 0,
                language: null,
                username: "imshantik5140",
                last_name: "Isaghoolian",
                first_name: "Shant",
                impact_points: 2100,
                project_supported: 0,
                identity_verified_at: "2025-05-15T00:00:00"
            },
            current: true,
            created_at: "2025-03-14T08:00:11.751864Z",
            updated_at: "2025-05-21T13:48:22.068189Z"
        },
        {
            id: "1396c403-1ade-4c40-b0d1-4680059a46c5",
            type: "organizations",
            meta: {
                bio: null,
                city: "Tehran",
                logo: {
                    id: "1b3fc1f9-234a-44fd-a087-b5ad37cdc647",
                    url: "https://storage.googleapis.com/socious-gcs/f63c207fad58219f0d89022ec3e4a614418063b25e29b97a4b03870e0c175892.jpg",
                    filename: "cover photo.jpg",
                    created_at: "2025-05-01T14:45:43.472183Z"
                },
                name: "OrganizationTest",
                cover: {},
                email: "imshantik@gmal.com",
                phone: null,
                status: "NOT_ACTIVE",
                address: null,
                country: "IR",
                culture: null,
                mission: null,
                website: "https://www.test",
                verified: false,
                shortname: "organizationtest",
                description: null,
                verified_impact: false
            },
            current: false,
            created_at: "2025-03-14T08:00:11.79032Z",
            updated_at: "2025-05-21T13:48:22.106495Z"
        },
        {
            id: "c750d7d3-f033-4ced-9924-b7c85698ca60",
            type: "organizations",
            meta: {
                bio: null,
                city: null,
                logo: {},
                name: "organizationfix",
                cover: {},
                email: "shantisaghoolian@gmail.com",
                phone: null,
                status: "NOT_ACTIVE",
                address: null,
                country: null,
                culture: null,
                mission: null,
                website: null,
                verified: false,
                shortname: "organizationfix",
                description: null,
                verified_impact: false
            },
            current: false,
            created_at: "2025-03-25T17:30:33.647357Z",
            updated_at: "2025-05-21T13:48:22.144234Z"
        },
        {
            id: "3a4aa78b-9bf1-41bc-ab9c-1ae4fd6ebc7d",
            type: "organizations",
            meta: {
                bio: "this is a test",
                city: "Tehran",
                logo: {},
                name: "shant company",
                cover: {},
                email: "mockMail@gmail.com",
                phone: null,
                status: "NOT_ACTIVE",
                address: null,
                country: "IR",
                culture: null,
                mission: null,
                website: "https://www.testingthiswebsite.com",
                verified: true,
                shortname: "shantik",
                description: null,
                verified_impact: false
            },
            current: false,
            created_at: "2025-03-14T08:00:11.802206Z",
            updated_at: "2025-05-21T13:48:22.125906Z"
        },
        {
            id: "bdb1f768-8127-4638-84f1-47a44e0b7f45",
            type: "organizations",
            meta: {
                bio: null,
                city: null,
                logo: {},
                name: "testorganization",
                cover: {},
                email: "shantisaghoolian@gmail.com",
                phone: null,
                status: "NOT_ACTIVE",
                address: null,
                country: null,
                culture: null,
                mission: null,
                website: null,
                verified: false,
                shortname: "testorganization",
                description: null,
                verified_impact: false
            },
            current: false,
            created_at: "2025-03-25T17:37:38.469126Z",
            updated_at: "2025-05-21T13:48:22.153642Z"
        },
        {
            id: "ae4e1517-b287-49e4-bfc3-618a38d3d45b",
            type: "organizations",
            meta: {
                bio: null,
                city: null,
                logo: {},
                name: "organizationfix",
                cover: {},
                email: "shantisaghoolian@gmail.com",
                phone: null,
                status: "NOT_ACTIVE",
                address: null,
                country: null,
                culture: null,
                mission: null,
                website: null,
                verified: false,
                shortname: "organizationfix",
                description: null,
                verified_impact: false
            },
            current: false,
            created_at: "2025-03-25T17:30:33.637558Z",
            updated_at: "2025-05-21T13:48:22.13528Z"
        },
        {
            id: "bf522d1a-9a47-4e98-803d-0ebd8482348a",
            type: "organizations",
            meta: {
                bio: null,
                city: null,
                logo: {},
                name: "Sennheiser",
                cover: {},
                email: "shantisaghoolian@gmail.com",
                phone: null,
                status: "NOT_ACTIVE",
                address: null,
                country: null,
                culture: null,
                mission: null,
                website: null,
                verified: true,
                shortname: "Sennheiser",
                description: null,
                verified_impact: false
            },
            current: false,
            created_at: "2025-03-26T09:33:19.916086Z",
            updated_at: "2025-05-21T13:48:22.172747Z"
        },
        {
            id: "dfbdc4e3-1a00-4f82-b07e-3079cc34c47f",
            type: "organizations",
            meta: {
                bio: null,
                city: null,
                logo: {
                    id: "6c5e9f7b-1eb3-4793-9bfb-4140c61b6918",
                    url: "https://storage.googleapis.com/socious-gcs/ed704342e2021407e83fb35e9c758bb7974f7171c7febf4c60a341092cb34b03.jpg",
                    filename: "images.jpg",
                    created_at: "2025-03-26T14:06:39.211836Z"
                },
                name: "Hunger",
                cover: {},
                email: "shantisaghoolian@gmail.com",
                phone: null,
                status: "NOT_ACTIVE",
                address: null,
                country: null,
                culture: null,
                mission: null,
                website: null,
                verified: false,
                shortname: "Hunger",
                description: null,
                verified_impact: false
            },
            current: false,
            created_at: "2025-03-26T16:48:21.103109Z",
            updated_at: "2025-05-21T13:48:22.182243Z"
        },
        {
            id: "f2df2626-12fb-4980-8410-44ec2027fdc8",
            type: "organizations",
            meta: {
                bio: null,
                city: null,
                logo: {},
                name: "ANewOrganization",
                cover: {},
                email: "vifufole@asciibinder.net",
                phone: null,
                status: "NOT_ACTIVE",
                address: null,
                country: null,
                culture: null,
                mission: null,
                website: null,
                verified: false,
                shortname: "ANewOrganization",
                description: null,
                verified_impact: false
            },
            current: false,
            created_at: "2025-05-01T14:48:47.236524Z",
            updated_at: "2025-05-21T13:48:22.116791Z"
        }
    ]
}

